# Generated by Django 5.0.3 on 2024-03-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
